### ISSUE TITLE
Probe Block - D2F-01F Microswitch

### ISSUE THREAD

**Issue by pacmac** [oldfar-t/Side-Swipe-Magnetic-Probe#1]
Hi, firstly thanks for your hard work.

I have the parts for this with the exception of the microswitch, I have omron D2F-01F in my stock, which is the same width but not as tall as the one you used.

This is the datasheet: https://www.mouser.sg/datasheet/2/307/en-d2f-587403.pdf

Would you be able to share the .step file for the probe block so that I can modify it for this switch, or if you prefer create a version that can use this microswitch :-)

Thanks again.

**Comment by pacmac** [comment]
<img width="1031" alt="Screenshot 2021-08-27 at 3 40 19 PM" src="https://user-images.githubusercontent.com/2349856/131091456-cd86a3f5-f5b2-4169-af25-c87fb6bae4db.png">
<img width="1234" alt="Screenshot 2021-08-27 at 3 22 55 PM" src="https://user-images.githubusercontent.com/2349856/131091473-b512e623-7c28-4e80-87b3-255eaa435b53.png">

The operating position is only different by 0.1mm

**Comment by pacmac** [comment]
Oh having just printed these parts, the microswitch seems to fit without modifications.

I presume that contact is made to the microswitch with the magnets, and that the microswitch contact pins are just resting, and not soldered or otherwise connected to the magnets ?

**Comment by oldfar-t** [comment]
> Oh having just printed these parts, the microswitch seems to fit without modifications.
> 
> I presume that contact is made to the microswitch with the magnets, and that the microswitch contact pins are just resting, and not soldered or otherwise connected to the magnets ?

Hey! I'm glad to hear! I'll work on getting the step files included anyway. Yes the micro switch should press fit in. You'll just need to trim the middle normally open contact. Once you press the switch in keeping just a little bit of the switch body exposed still you'll bend the legs of the switch over and press the magnets in.
