### ISSUE TITLE
Movement path blocked by light bar

### ISSUE THREAD

**Issue by MichaelMichaelMichaelMichaelMichael** [oldfar-t/Side-Swipe-Magnetic-Probe#8]
Hi, I have a problem using the otherwise fantastic side-swipe-magnetic-probe: it's movement path is being blocked by the lighting which I have mounted like shown in the pictures. It's not possible to mount the servo lower because of the required operation height. 
Do you have any advice other than removing the light? 

![3d-sideswipe-1](https://user-images.githubusercontent.com/4020552/170602288-4c06722f-f9c2-4eba-92a8-91b18420d2f1.jpg)
![3d-sideswipe-2](https://user-images.githubusercontent.com/4020552/170602289-baa1879f-8f2f-44a3-8204-2b3ca6b94ac8.jpg)
Thank you in advance

**Comment by oldfar-t** [comment]
Hi! That is an interesting problem since you can't just move the assembly further down. Do you have lighting on both sides of the frame? You could mirror the printed parts and mount the side swipe mechanism to the left side of the frame.

**Comment by MichaelMichaelMichaelMichaelMichael** [comment]
Well, the light bars are on both sides, but meanwhile I've changed my mind and I will put my light bars higher. Not all mods can necessarily be combined with each other. Thank you nonetheless for having had a second set of eyes on that.
